# python -m train --config-name=longcrawl_v4-32_31m +paths.model_name=31m
defaults:
- longcrawl_base
- _self_

num_hosts: 1

mesh:
  d: 1 
  t: 1

training:
  warmup_steps: 3840 
  steps:        38400 
  steps_for_lr: 38400 
  learning_rate: 7.3e-3
  tokens:
    batch: 4 
    len: 4096 

model:
  d_model: 256 
  n_q_per_kv: 1
  n_kv: 16 
  d_head: 64 
  d_ff: 1024 
  layers: 8
  vocab: 50304
  rope_max_timescale: 10000

longcrawl:
  path: "/mnt/HDD/longcrawl64/data"

paths:
  root_working_dir: "/mnt/SSD/seqax_outputs"

checkpoint_interval: 4000 